import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

const Layout = ({title, children}) => {
    return (
        <div>
            <Head>
                <title>{title} | Bicentenario Afroperuanos</title>
                {/* <link rel="icon" href="/assets/img/favicon/logo.ico" /> */}
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="/styles/css/comparison.css"></link>
            </Head>
            <main>
                {children}
            </main>
        </div>
    )
}

export default Layout